// 샘플 데모 데이터
export const demoGames = [
  {
    id: "game1",
    gameId: 5623589245,
    gameVersion: "15.8.1",
    gameDuration: 1865, // 약 31분
    teams: [
      { teamId: 100, win: true },
      { teamId: 200, win: false }
    ],
    participants: [
      {
        summonerId: "player1",
        summonerName: "탑솔킹",
        championId: 114,
        championName: "Fiora",
        individualPosition: "TOP",
        teamId: 100,
        win: true,
        kills: 7,
        deaths: 3,
        assists: 4,
        totalMinionsKilled: 221,
        goldEarned: 12450,
        totalDamageDealtToChampions: 24650,
        totalDamageTaken: 18700,
        visionScore: 21,
        wardsPlaced: 6,
        wardsKilled: 2
      },
      {
        summonerId: "player2",
        summonerName: "정글잘함",
        championId: 64,
        championName: "Lee Sin",
        individualPosition: "JUNGLE",
        teamId: 100,
        win: true,
        kills: 5,
        deaths: 2,
        assists: 13,
        totalMinionsKilled: 156,
        goldEarned: 10870,
        totalDamageDealtToChampions: 14780,
        totalDamageTaken: 22300,
        visionScore: 35,
        wardsPlaced: 12,
        wardsKilled: 7
      },
      {
        summonerId: "player3",
        summonerName: "미드일잘",
        championId: 157,
        championName: "Yasuo",
        individualPosition: "MIDDLE",
        teamId: 100,
        win: true,
        kills: 11,
        deaths: 4,
        assists: 7,
        totalMinionsKilled: 245,
        goldEarned: 13560,
        totalDamageDealtToChampions: 28450,
        totalDamageTaken: 15600,
        visionScore: 18,
        wardsPlaced: 5,
        wardsKilled: 1
      },
      {
        summonerId: "player4",
        summonerName: "원딜천재",
        championId: 236,
        championName: "Lucian",
        individualPosition: "BOTTOM",
        teamId: 100,
        win: true,
        kills: 9,
        deaths: 2,
        assists: 8,
        totalMinionsKilled: 267,
        goldEarned: 14250,
        totalDamageDealtToChampions: 31780,
        totalDamageTaken: 12400,
        visionScore: 14,
        wardsPlaced: 4,
        wardsKilled: 0
      },
      {
        summonerId: "player5",
        summonerName: "서폿장인",
        championId: 412,
        championName: "Thresh",
        individualPosition: "UTILITY",
        teamId: 100,
        win: true,
        kills: 1,
        deaths: 6,
        assists: 24,
        totalMinionsKilled: 42,
        goldEarned: 8750,
        totalDamageDealtToChampions: 7650,
        totalDamageTaken: 16800,
        visionScore: 78,
        wardsPlaced: 28,
        wardsKilled: 11
      },
      {
        summonerId: "player6",
        summonerName: "상대탑",
        championId: 122,
        championName: "Darius",
        individualPosition: "TOP",
        teamId: 200,
        win: false,
        kills: 4,
        deaths: 6,
        assists: 3,
        totalMinionsKilled: 195,
        goldEarned: 9780,
        totalDamageDealtToChampions: 15430,
        totalDamageTaken: 22300,
        visionScore: 12,
        wardsPlaced: 3,
        wardsKilled: 1
      },
      {
        summonerId: "player7",
        summonerName: "상대정글",
        championId: 11,
        championName: "Master Yi",
        individualPosition: "JUNGLE",
        teamId: 200,
        win: false,
        kills: 8,
        deaths: 7,
        assists: 4,
        totalMinionsKilled: 178,
        goldEarned: 11230,
        totalDamageDealtToChampions: 18920,
        totalDamageTaken: 21400,
        visionScore: 22,
        wardsPlaced: 8,
        wardsKilled: 3
      },
      {
        summonerId: "player8",
        summonerName: "상대미드",
        championId: 245,
        championName: "Ekko",
        individualPosition: "MIDDLE",
        teamId: 200,
        win: false,
        kills: 6,
        deaths: 8,
        assists: 7,
        totalMinionsKilled: 212,
        goldEarned: 10450,
        totalDamageDealtToChampions: 19840,
        totalDamageTaken: 17850,
        visionScore: 19,
        wardsPlaced: 5,
        wardsKilled: 2
      },
      {
        summonerId: "player9",
        summonerName: "상대원딜",
        championId: 29,
        championName: "Twitch",
        individualPosition: "BOTTOM",
        teamId: 200,
        win: false,
        kills: 7,
        deaths: 5,
        assists: 4,
        totalMinionsKilled: 243,
        goldEarned: 12180,
        totalDamageDealtToChampions: 24560,
        totalDamageTaken: 13200,
        visionScore: 16,
        wardsPlaced: 5,
        wardsKilled: 0
      },
      {
        summonerId: "player10",
        summonerName: "상대서폿",
        championId: 40,
        championName: "Janna",
        individualPosition: "UTILITY",
        teamId: 200,
        win: false,
        kills: 0,
        deaths: 7,
        assists: 14,
        totalMinionsKilled: 21,
        goldEarned: 7450,
        totalDamageDealtToChampions: 5340,
        totalDamageTaken: 12600,
        visionScore: 65,
        wardsPlaced: 23,
        wardsKilled: 8
      }
    ]
  },
  {
    id: "game2",
    gameId: 5623589246,
    gameVersion: "15.8.1",
    gameDuration: 2134, // 약 35분
    teams: [
      { teamId: 100, win: false },
      { teamId: 200, win: true }
    ],
    participants: [
      {
        summonerId: "player1",
        summonerName: "탑솔킹",
        championId: 54,
        championName: "Malphite",
        individualPosition: "TOP",
        teamId: 100,
        win: false,
        kills: 2,
        deaths: 5,
        assists: 9,
        totalMinionsKilled: 187,
        goldEarned: 9870,
        totalDamageDealtToChampions: 14320,
        totalDamageTaken: 27600,
        visionScore: 18,
        wardsPlaced: 5,
        wardsKilled: 1
      },
      {
        summonerId: "player2",
        summonerName: "정글잘함",
        championId: 104,
        championName: "Graves",
        individualPosition: "JUNGLE",
        teamId: 100,
        win: false,
        kills: 8,
        deaths: 6,
        assists: 7,
        totalMinionsKilled: 192,
        goldEarned: 12450,
        totalDamageDealtToChampions: 21760,
        totalDamageTaken: 19800,
        visionScore: 32,
        wardsPlaced: 11,
        wardsKilled: 6
      },
      {
        summonerId: "player3",
        summonerName: "미드일잘",
        championId: 238,
        championName: "Zed",
        individualPosition: "MIDDLE",
        teamId: 100,
        win: false,
        kills: 9,
        deaths: 7,
        assists: 4,
        totalMinionsKilled: 221,
        goldEarned: 12870,
        totalDamageDealtToChampions: 25430,
        totalDamageTaken: 14750,
        visionScore: 21,
        wardsPlaced: 6,
        wardsKilled: 2
      },
      {
        summonerId: "player4",
        summonerName: "원딜천재",
        championId: 21,
        championName: "Miss Fortune",
        individualPosition: "BOTTOM",
        teamId: 100,
        win: false,
        kills: 6,
        deaths: 4,
        assists: 5,
        totalMinionsKilled: 234,
        goldEarned: 11980,
        totalDamageDealtToChampions: 23450,
        totalDamageTaken: 13600,
        visionScore: 13,
        wardsPlaced: 3,
        wardsKilled: 0
      },
      {
        summonerId: "player5",
        summonerName: "서폿장인",
        championId: 432,
        championName: "Bard",
        individualPosition: "UTILITY",
        teamId: 100,
        win: false,
        kills: 2,
        deaths: 8,
        assists: 17,
        totalMinionsKilled: 31,
        goldEarned: 8120,
        totalDamageDealtToChampions: 9870,
        totalDamageTaken: 18900,
        visionScore: 82,
        wardsPlaced: 31,
        wardsKilled: 9
      },
      {
        summonerId: "player6",
        summonerName: "상대탑",
        championId: 92,
        championName: "Riven",
        individualPosition: "TOP",
        teamId: 200,
        win: true,
        kills: 9,
        deaths: 4,
        assists: 6,
        totalMinionsKilled: 231,
        goldEarned: 14320,
        totalDamageDealtToChampions: 26780,
        totalDamageTaken: 21300,
        visionScore: 17,
        wardsPlaced: 4,
        wardsKilled: 1
      },
      {
        summonerId: "player7",
        summonerName: "상대정글",
        championId: 35,
        championName: "Shaco",
        individualPosition: "JUNGLE",
        teamId: 200,
        win: true,
        kills: 12,
        deaths: 5,
        assists: 11,
        totalMinionsKilled: 173,
        goldEarned: 14890,
        totalDamageDealtToChampions: 24350,
        totalDamageTaken: 16700,
        visionScore: 29,
        wardsPlaced: 10,
        wardsKilled: 5
      },
      {
        summonerId: "player8",
        summonerName: "상대미드",
        championId: 7,
        championName: "LeBlanc",
        individualPosition: "MIDDLE",
        teamId: 200,
        win: true,
        kills: 8,
        deaths: 7,
        assists: 9,
        totalMinionsKilled: 198,
        goldEarned: 13240,
        totalDamageDealtToChampions: 28760,
        totalDamageTaken: 15900,
        visionScore: 23,
        wardsPlaced: 7,
        wardsKilled: 3
      },
      {
        summonerId: "player9",
        summonerName: "상대원딜",
        championId: 145,
        championName: "Kai'Sa",
        individualPosition: "BOTTOM",
        teamId: 200,
        win: true,
        kills: 11,
        deaths: 3,
        assists: 7,
        totalMinionsKilled: 267,
        goldEarned: 15670,
        totalDamageDealtToChampions: 32450,
        totalDamageTaken: 14300,
        visionScore: 18,
        wardsPlaced: 5,
        wardsKilled: 1
      },
      {
        summonerId: "player10",
        summonerName: "상대서폿",
        championId: 25,
        championName: "Morgana",
        individualPosition: "UTILITY",
        teamId: 200,
        win: true,
        kills: 2,
        deaths: 4,
        assists: 23,
        totalMinionsKilled: 38,
        goldEarned: 9870,
        totalDamageDealtToChampions: 12340,
        totalDamageTaken: 15600,
        visionScore: 76,
        wardsPlaced: 28,
        wardsKilled: 11
      }
    ]
  },
  {
    id: "game3",
    gameId: 5623589247,
    gameVersion: "15.8.1",
    gameDuration: 1732, // 약 29분
    teams: [
      { teamId: 100, win: true },
      { teamId: 200, win: false }
    ],
    participants: [
      {
        summonerId: "player1",
        summonerName: "탑솔킹",
        championId: 86,
        championName: "Garen",
        individualPosition: "TOP",
        teamId: 100,
        win: true,
        kills: 5,
        deaths: 2,
        assists: 7,
        totalMinionsKilled: 197,
        goldEarned: 11340,
        totalDamageDealtToChampions: 19870,
        totalDamageTaken: 24500,
        visionScore: 19,
        wardsPlaced: 5,
        wardsKilled: 1
      },
      {
        summonerId: "player2",
        summonerName: "정글잘함",
        championId: 121,
        championName: "Kha'Zix",
        individualPosition: "JUNGLE",
        teamId: 100,
        win: true,
        kills: 12,
        deaths: 4,
        assists: 9,
        totalMinionsKilled: 165,
        goldEarned: 13680,
        totalDamageDealtToChampions: 24780,
        totalDamageTaken: 17900,
        visionScore: 28,
        wardsPlaced: 9,
        wardsKilled: 5
      },
      {
        summonerId: "player3",
        summonerName: "미드일잘",
        championId: 101,
        championName: "Xerath",
        individualPosition: "MIDDLE",
        teamId: 100,
        win: true,
        kills: 8,
        deaths: 3,
        assists: 11,
        totalMinionsKilled: 232,
        goldEarned: 12890,
        totalDamageDealtToChampions: 32450,
        totalDamageTaken: 12300,
        visionScore: 24,
        wardsPlaced: 7,
        wardsKilled: 2
      },
      {
        summonerId: "player4",
        summonerName: "원딜천재",
        championId: 67,
        championName: "Vayne",
        individualPosition: "BOTTOM",
        teamId: 100,
        win: true,
        kills: 14,
        deaths: 3,
        assists: 5,
        totalMinionsKilled: 243,
        goldEarned: 14760,
        totalDamageDealtToChampions: 29870,
        totalDamageTaken: 13700,
        visionScore: 15,
        wardsPlaced: 4,
        wardsKilled: 0
      },
      {
        summonerId: "player5",
        summonerName: "서폿장인",
        championId: 16,
        championName: "Soraka",
        individualPosition: "UTILITY",
        teamId: 100,
        win: true,
        kills: 1,
        deaths: 5,
        assists: 26,
        totalMinionsKilled: 24,
        goldEarned: 8960,
        totalDamageDealtToChampions: 8760,
        totalDamageTaken: 14300,
        visionScore: 74,
        wardsPlaced: 29,
        wardsKilled: 8
      },
      {
        summonerId: "player6",
        summonerName: "상대탑",
        championId: 14,
        championName: "Sion",
        individualPosition: "TOP",
        teamId: 200,
        win: false,
        kills: 2,
        deaths: 6,
        assists: 6,
        totalMinionsKilled: 187,
        goldEarned: 9240,
        totalDamageDealtToChampions: 14560,
        totalDamageTaken: 28700,
        visionScore: 16,
        wardsPlaced: 4,
        wardsKilled: 0
      },
      {
        summonerId: "player7",
        summonerName: "상대정글",
        championId: 254,
        championName: "Vi",
        individualPosition: "JUNGLE",
        teamId: 200,
        win: false,
        kills: 6,
        deaths: 8,
        assists: 9,
        totalMinionsKilled: 142,
        goldEarned: 10320,
        totalDamageDealtToChampions: 17890,
        totalDamageTaken: 22400,
        visionScore: 25,
        wardsPlaced: 8,
        wardsKilled: 4
      },
      {
        summonerId: "player8",
        summonerName: "상대미드",
        championId: 34,
        championName: "Anivia",
        individualPosition: "MIDDLE",
        teamId: 200,
        win: false,
        kills: 5,
        deaths: 6,
        assists: 8,
        totalMinionsKilled: 208,
        goldEarned: 11240,
        totalDamageDealtToChampions: 21980,
        totalDamageTaken: 16700,
        visionScore: 22,
        wardsPlaced: 6,
        wardsKilled: 3
      },
      {
        summonerId: "player9",
        summonerName: "상대원딜",
        championId: 18,
        championName: "Tristana",
        individualPosition: "BOTTOM",
        teamId: 200,
        win: false,
        kills: 9,
        deaths: 7,
        assists: 3,
        totalMinionsKilled: 231,
        goldEarned: 12340,
        totalDamageDealtToChampions: 25670,
        totalDamageTaken: 15400,
        visionScore: 14,
        wardsPlaced: 3,
        wardsKilled: 0
      },
      {
        summonerId: "player10",
        summonerName: "상대서폿",
        championId: 78,
        championName: "Poppy",
        individualPosition: "UTILITY",
        teamId: 200,
        win: false,
        kills: 3,
        deaths: 13,
        assists: 11,
        totalMinionsKilled: 42,
        goldEarned: 8240,
        totalDamageDealtToChampions: 11240,
        totalDamageTaken: 21300,
        visionScore: 56,
        wardsPlaced: 21,
        wardsKilled: 6
      }
    ]
  }
]; 